/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kenvix_walk_JniMain */

#ifndef _Included_com_kenvix_walk_JniMain
#define _Included_com_kenvix_walk_JniMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kenvix_walk_JniMain
 * Method:    onApplicationStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kenvix_walk_JniMain_onApplicationStart
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
